Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('', include('home.urls', namespace='home')),
                  path('additem/', include('ad_item.urls', namespace='ad_item')),
                  path('products/', include('product.urls', namespace='product')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    path('search/', views.search_results, name='search_results'),
    path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from datetime import datetime

from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.shortcuts import render


from ad_item.models import Item
from .models import *
from ad_item.models import Item


def home_view(request):
  # نمایش ۶ آیتم برتر
    return render(request, 'home/home.html', {

    })

from django.shortcuts import render
from django.core.paginator import Paginator
def search_results(request):
    query = request.GET.get('q')
    items = Item.objects.filter(title__icontains=query) if query else []
    paginator = Paginator(items, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'home/search_result.html', {'query': query, 'items': page_obj,})




def product_detail(request, id):
    item = get_object_or_404(Item, id = id)
    collateral_type = item.collateral_types.all()
    total_price = None
    days = None

    quantity = None
    error_message = None

    if request.method == 'POST':
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        quantity = int(request.POST.get('quantity', 0))

        if start_date and end_date and quantity > 0:
            start_date = datetime.strptime(start_date, '%Y-%m-%d')
            end_date = datetime.strptime(end_date, '%Y-%m-%d')
            days = (end_date - start_date).days

            if days > 0:
                if quantity <= item.quantity_available:
                    total_price = days * item.price_per_day * quantity
                else:
                    error_message = "The requested quantity exceeds available stock."
            else:
                error_message = "End date must be after start date."
        else:
            error_message = "Please fill out all fields correctly."

    return render(request, 'product/detail_product.html', {
        'item': item,
        'days': days,
        'quantity': quantity,
        'total_price': total_price,
        'error_message': error_message,
        'collateral_type': collateral_type,
    })

home/templates/home/home.html
{% extends '_base.html' %}
{% load static %}
{% block css %}
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'home/home/home.css' %}">
    <link href="{% static 'home/searchbar/searchbar.css' %}" rel="stylesheet"/>
{% endblock %}


{% block body %}



    <header class=" text-white text-center py-5">
        <div class="container-fluid">
            <h1 class="display-4 mb-3">به سایت اجاره چی خوش آمدید</h1>
            <br>
            <h2 class="">اینجا میتونید <strong class="text-warning">   همه چی</strong> رو اجاره بدین یا اجاره کنید</h2>
        </div>
    </header>






    <div class="s006">
        <form method="get" action="{% url 'home:search_results' %}" >
            <fieldset>
                <legend class=""> دنبال چی میگردین؟</legend>
                <div class="inner-form">
                    <div class="input-field">
                        <button class="btn-search" type="button">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                            </svg>
                        </button>
                        <input name="q" id="search" class="searchinp" type="text" placeholder=""/>
                    </div>
                </div>

            </fieldset>
        </form>
    </div>







{% endblock %}

home/templates/home/search_result.html
{% extends '_base.html' %}
{% load static %}

{% block css %}
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'home/home/home.css' %}">
{% endblock %}

{% block body %}
    <div class="search-results mt-5">
        <h2 class="text-white">نتایج جستجو برای: "{{ query }}"</h2>
        <div class="container">
            <div class="row">
                {% if items %}
                    {% for item in items %}
                        <div class="col-12 col-md-6 col-lg-4 mb-4">
                            <div class="card">
                                {% if item.images.all %}
                                    <img src="{{ item.images.first.image.url }}" class="card-img-top"
                                         alt="{{ item.title }}"
                                         style="max-height: 200px; object-fit: cover;">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title">{{ item.title }}</h5>
                                    <p class="card-text text-muted">{{ item.description|truncatewords:15 }}</p>
                                    <p class="text-success">${{ item.price_per_day }} / روز </p>
                                    <p class="text-success">${{ item.created_at }}</p>
                                    <a href="{% url 'product:product_detail' item.id %}"
                                       class="btn btn-primary">جزئیات</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <nav class="mt-4">
                        <ul class="pagination justify-content-center">
                            {% if items.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?q={{ query }}&page=1">&laquo; اولی</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" href="?q={{ query }}&page={{ items.previous_page_number }}">قبلی</a>
                                </li>
                            {% endif %}
                            {% if items.has_next %}
                                <li class="page-item">
                                    <a class="page-link"
                                       href="?q={{ query }}&page={{ items.next_page_number }}">بعدی</a>
                                </li>

                            {% endif %}
                            {% for page_num in items.paginator.page_range %}
                                {% if items.number == page_num %}
                                    <li class="page-item active">
                                        <span class="page-link">{{ page_num }}</span>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link"
                                           href="?q={{ query }}&page={{ page_num }}">{{ page_num }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                          {% if items.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?q={{ query }}&page={{ items.paginator.num_pages }}">آخرین
                                    &raquo;</a>
                            </li>
                            {% endif %}
                        </ul>

                    </nav>
                {% else %}
                    <p class="text-white">نتیجه‌ای پیدا نشد.</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}