Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('', include('home.urls', namespace='home')),
                  path('additem/', include('ad_item.urls', namespace='ad_item')),
                  path('products/', include('product.urls', namespace='product')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

ad_item/urls.py
from django.urls import path


from . import views

app_name='add_item'

urlpatterns = [
    path('add-item/', views.add_item, name='add_item'),
]

home/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    path('search/', views.search_results, name='search_results'),
    path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
]

ad_item/models.py
from datetime import timezone

from django.conf import settings
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User

# models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    title = models.CharField(max_length=255)
    description = models.TextField()
    quantity_available = models.PositiveIntegerField(default=1)
    item_value = models.PositiveIntegerField(default=0)
    price_per_day = models.DecimalField(max_digits=10, decimal_places=2)
    province = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True , null=True , blank=True)
    address = models.TextField()
    collateral_required = models.BooleanField(default=False)
    collateral_types = models.ManyToManyField('Collateral', blank=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='items', null=True, blank=True , default=1)  # تغییر به null=True
    latitude = models.FloatField(null=True, blank=True)  # عرض جغرافیایی
    longitude = models.FloatField(null=True, blank=True)  # طول جغرافیایی

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to='product_images/', max_length=200)


class Collateral(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

ad_item/forms.py
from django import forms
from .models import *

# forms.py
from django import forms
from django.forms.models import inlineformset_factory

from .models import *

class ItemForm(forms.ModelForm):
    collateral_types = forms.ModelMultipleChoiceField(
        queryset=Collateral.objects.all(),
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}),
        required=False
    )

    class Meta:
        model = Item
        fields = [
            'category', 'title', 'description', 'quantity_available',
            'province', 'city', 'address', 'collateral_required',
            'collateral_types', 'price_per_day',
            'item_value',


        ]
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'quantity_available': forms.NumberInput(attrs={'class': 'form-control'}),
            'province': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
            'collateral_required': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'price_per_day': forms.NumberInput(attrs={'class': 'form-control'}),
            'item_value': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image']

ad_item/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ItemForm
from .models import ProductImage, Collateral


@login_required
def add_item(request):
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            # ذخیره محصول بدون ثبت نهایی
            product = form.save(commit=False)

            # افزودن اطلاعات کاربر و موقعیت مکانی
            product.owner = request.user
            product.latitude = request.POST.get('latitude')
            product.longitude = request.POST.get('longitude')

            # ذخیره محصول
            product.save()
            form.save_m2m()  # ذخیره روابط ManyToMany

            # ذخیره تصاویر
            images = request.FILES.getlist('images')
            for image in images:
                ProductImage.objects.create(product=product, image=image)

            return redirect('home:home')
    else:
        form = ItemForm()

    # ارسال اطلاعات وثیقه‌ها برای استفاده در قالب
    collaterals = Collateral.objects.all()
    return render(
        request,
        'add_item/add_item.html',
        {'form': form, 'collaterals': collaterals}
    )

ad_item/templates/add_item/add_item.html
{% extends '_base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'ad-item/additem1.css' %}">
{% endblock %}
{% block body %}
    <style>

    </style>
    <div class="container mt-5 text-white">
        <h2 class="mb-4"> ثبت محصول</h2>
        <form method="POST" enctype="multipart/form-data" id="productForm">
            {% csrf_token %}

            <!-- Nav Tabs -->
            <ul class="nav nav-tabs mb-4" id="productTabs" role="tablist">
                <li class="nav-item">
                    <button class="nav-link active" id="general-tab" data-bs-toggle="tab" data-bs-target="#general"
                            type="button" role="tab" aria-controls="general" aria-selected="true">
                        مشخصات
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" id="images-tab" data-bs-toggle="tab" data-bs-target="#images2"
                            type="button"
                            role="tab" aria-controls="images" aria-selected="false">
                        تصاویر
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" id="location-tab" data-bs-toggle="tab" data-bs-target="#location"
                            type="button" role="tab" aria-controls="location" aria-selected="false">
                        موقعیت مکانی
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" id="collateral-tab" data-bs-toggle="tab" data-bs-target="#collateral"
                            type="button" role="tab" aria-controls="collateral" aria-selected="false">
                        وثیقه
                    </button>
                </li>
                <li class="nav-item">
                    <button class="nav-link" id="pricing-tab" data-bs-toggle="tab" data-bs-target="#pricing"
                            type="button" role="tab" aria-controls="pricing" aria-selected="false">
                        هزینه اجاره
                    </button>
                </li>
            </ul>

            <!-- Tab Content -->
            <div class="tab-content" id="productTabsContent">
                <!-- اطلاعات عمومی -->
                <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
                    <div class="form-group mb-3">
                        {{ form.category.label }}<br>
                        {{ form.category }}
                    </div>
                    <div class="form-group mb-3">
                        {{ form.title.label }}<br>
                        {{ form.title }}
                    </div>
                    <div class="form-group mb-3">
                        {{ form.description.label }}<br>
                        {{ form.description }}
                    </div>
                    <div class="form-group mb-3">
                        {{ form.quantity_available.label }}<br>
                        {{ form.quantity_available }}
                    </div>
                    <button type="button" class="btn btn-primary next-tab">بعدی</button>
                </div>

                <!-- تصاویر -->
                <div class="tab-pane fade" id="images2" role="tabpanel" aria-labelledby="images-tab">
                    <div class="form-group mb-3">
                        {{ form.images.label }}<br>
                        <input type="file" name="images" id="images" multiple>

                    </div>
                    <div id="imagePreviewContainer" class="d-flex flex-wrap gap-3 mt-3">

                    </div>
                    <br>
                    <button type="button" class="btn btn-secondary prev-tab">برگشت</button>
                    <button type="button" class="btn btn-primary next-tab">بعدی</button>
                </div>

                <!-- موقعیت مکانی -->
                <div class="tab-pane fade" id="location" role="tabpanel" aria-labelledby="location-tab">
                    <div class="form-group mb-3">
                        <label for="province">استان:</label>
                        <select id="province" name="province" class="form-control">
                            <option value="">لطفاً استان را انتخاب کنید</option>
                            <!-- استان‌ها به‌صورت پویا بارگذاری می‌شوند -->
                        </select>
                    </div>

                  <div class="form-group mb-3">
                        <label for="city">شهر:</label>
                        <select id="city" name="city" class="form-control" disabled>
                            <option value="">لطفاً ابتدا استان را انتخاب کنید</option>
                            <!-- شهرها به‌صورت پویا بارگذاری می‌شوند -->
                        </select>
                    </div>
                    <div class="form-group mb-3">
                        {{ form.address.label }}<br>
                        {{ form.address }}
                    </div>
                    <button type="button" class="btn btn-secondary prev-tab">برگشت</button>
                    <button type="button" class="btn btn-primary next-tab">بعدی</button>
                </div>

                <!-- وثیقه -->
                <div class="tab-pane fade" id="collateral" role="tabpanel" aria-labelledby="collateral-tab">
                    <h4>موارد وثیقه</h4>
                    <div class="form-check">
                        <input type="checkbox" name="collateral_required" class="form-check-input"
                               id="id_collateral_required">
                        <label class="form-check-label" for="id_collateral_required">آیا وثیقه نیاز است؟</label>

                    </div>
                    <div>
                        {% for collateral in form.collateral_types %}
                            <div class="form-check">
                                {{ collateral.tag }}
                                <label class="form-check-label"
                                       for="{{ collateral.id }}">{{ collateral.choice_label }}</label>
                            </div>
                        {% endfor %}
                    </div>
                    <button type="button" class="btn btn-secondary prev-tab">برگشت</button>
                    <button type="button" class="btn btn-primary next-tab">بعدی</button>
                </div>

                <!-- هزینه اجاره -->
                <div class="tab-pane fade" id="pricing" role="tabpanel" aria-labelledby="pricing-tab">
                    <div class="form-group mb-3">
                        قیمت برای هر یک روز
                        {{ form.price_per_day }}
                        <br>
                        کل ارزش محصول
                        {{ form.item_value }}
                    </div>
                    <button type="button" class="btn btn-secondary prev-tab">برگشت</button>
                    <button type="submit" class="btn btn-success">ثبت محصول</button>
                </div>
            </div>
        </form>
    </div>


    <script src="{% static 'ad-item/aditem.js' %}">

    </script>
{% endblock %}