Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('', include('home.urls', namespace='home')),
                  path('additem/', include('ad_item.urls', namespace='ad_item')),
                  path('products/', include('product.urls', namespace='product')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.update_profile, name='update'),
    path('Change_password/', views.change_password, name='change_password'),
    path('saved/', views.saved, name='saved'),
]

ad_item/urls.py
from django.urls import path


from . import views

app_name='add_item'

urlpatterns = [
    path('add-item/', views.add_item, name='add_item'),
]

home/urls.py
from django.urls import path

from . import views
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
    path('search/', views.search_results, name='search_results'),
    path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
]

product/urls.py
from django.urls import path
from . import views



app_name = 'product'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('product_detail/<int:id>/', views.product_detail, name='product_detail'),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
          integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-+qdLaIRZfNu4cVPK/PxJJEy0B0f3Ugv8i482AKY7gwXwhaCroABd086ybrVKTa0q" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/persian-datepicker@1.2.0/dist/css/persian-datepicker.min.css">
        <link rel="stylesheet" href="{% static 'base/_base2.css' %} ">


    {% block css %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="container">
    {% include 'messages.html' %}
    {% block body %}
    {% endblock %}
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>



</body>
</html>

templates/messages.html
{% if messages %}
    {% for msg in messages %}
        <h3 {% if msg.tags %} class="alert alert-{{ msg.tags }}"{% endif %}>{{ msg }}</h3>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ">
    <div class="container-fluid mx-5">
        <a class="navbar-brand" href="{% url 'home:home' %}">اجاره‌چی</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link fs-5" href="{% url 'product:product_list' %}">اجاره کن</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link fs-5" href="{% url 'ad_item:add_item' %}">اجاره بده</a>
                </li>
                {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link fs-5" href="{% url 'accounts:profile' %}">حساب کاربری</a>
                    </li>
{% comment %}
                    <a  class="mt-3"><i  class="bi bi-bookmark-fill fs-5 "></i></a>
{% endcomment %}

                    <a class="nav-link fs-5" href="{% url 'accounts:logout' %}">خروج</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link fs-5" href="{% url 'accounts:register' %}">ثبت نام</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link fs-5" href="{% url 'accounts:login' %}">ورود</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>